const SENSOR_LIST_REQUEST = "SENSOR_LIST_REQUEST";
const SENSOR_LIST_SUCESS = "SENSOR_LIST_SUCESS";
const SENSOR_LIST_FAIL = "SENSOR_LIST_FAIL";

const SENSOR_DETAILS_REQUEST = "SENSOR_DETAILS_REQUEST";
const SENSOR_DETAILS_SUCESS = "SENSORDETAILST_SUCESS";
const SENSOR_DETAILS_FAIL = "SENSOR_DETAILS_FAIL";

const SENSOR_DELETE_REQUEST = "SENSOR_DELETE_REQUEST";
const SENSOR_DELETE_SUCESS = "SENSOR_DELETE_SUCESS";
const SENSOR_DELETE_FAIL = "SENSOR_DELETE_FAIL";

const SENSOR_ALERT_REQUEST = "SENSOR_ALERT_REQUEST";
const SENSOR_ALERT_SUCCESS = "SENSOR_ALERT_SUCCESS";
const SENSOR_ALERT_ERROR = "SENSOR_ALERT_ERROR";

const SENSOR_SAVE_REQUEST = "SENSOR_SAVE_REQUEST";
const SENSOR_SAVE_SUCCESS = "SENSOR_SAVE_SUCCESS";
const SENSOR_SAVE_ERROR = "SENSOR_SAVE_ERROR";


export {
  SENSOR_LIST_FAIL,
  SENSOR_LIST_SUCESS,
  SENSOR_LIST_REQUEST,
  SENSOR_DETAILS_FAIL,
  SENSOR_DETAILS_REQUEST,
  SENSOR_DETAILS_SUCESS,
  SENSOR_DELETE_FAIL,
  SENSOR_DELETE_REQUEST,
  SENSOR_DELETE_SUCESS,
  SENSOR_ALERT_REQUEST,
  SENSOR_ALERT_SUCCESS,
  SENSOR_ALERT_ERROR,
  SENSOR_SAVE_SUCCESS,
  SENSOR_SAVE_ERROR,
  SENSOR_SAVE_REQUEST
};