const SENSOR_LIST_REQUEST = "SENSOR_LIST_REQUEST";
const SENSOR_LIST_SUCESS = "SENSOR_LIST_SUCESS";
const SENSOR_LIST_FAIL = "SENSOR_LIST_FAIL";

const SENSOR_DETAILS_REQUEST = "SENSOR_DETAILS_REQUEST";
const SENSOR_DETAILS_SUCESS = "SENSORDETAILST_SUCESS";
const SENSOR_DETAILS_FAIL = "SENSOR_DETAILS_FAIL";


export {
  SENSOR_LIST_FAIL,
  SENSOR_LIST_SUCESS,
  SENSOR_LIST_REQUEST,
  SENSOR_DETAILS_FAIL,
  SENSOR_DETAILS_REQUEST,
  SENSOR_DETAILS_SUCESS
};